[View in Colaboratory](https://colab.research.google.com/github/MedSalahBT/cours-insa/blob/master/TP3_optim_starter_kit.ipynb)

In [1]:
!pip install cvxpy

    100% |████████████████████████████████| 901kB 16.2MB/s 
    100% |████████████████████████████████| 153kB 26.4MB/s 
    100% |████████████████████████████████| 122kB 28.6MB/s 
    100% |████████████████████████████████| 143kB 29.1MB/s 
    100% |████████████████████████████████| 1.4MB 6.2MB/s 
  Running setup.py bdist_wheel for cvxpy ... - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - done
  Stored in directory: /root/.cache/pip/wheels/10/e3/64/e65da213c6af18e1fd78d51482236a85207ff25962146e302f
  Running setup.py bdist_wheel for ecos ... - \ | / - \ | / - \ | / - \ | / - \ | / - \ | done
  Stored in directory: /root/.cache/pip/wheels/50/91/1b/568de3c087b3399b03d130e71b1fd048ec072c45f72b6b6e9a
  Running setup.py bdist_wheel for scs ... - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ |

In [0]:
import scipy as sc
import numpy as np
import cvxpy as cvx


In [3]:
# http://www.vision.ime.usp.br/~igor/articles/convex-optimization.html

x = cvx.Variable(1)
y = cvx.Variable(1)
prob = cvx.Problem(cvx.Minimize(30*x+20*y),[
        8*x+12*y >=24,
        12*x + 12*y >=36,
        2*x + y >= 4,
        x + y <= 5,
        x>=0,y>=0])
sol = prob.solve()
print((x.value,y.value))


# https://www.cvxpy.org/tutorial/advanced/index.html

x = cvx.Variable(1)
y = cvx.Variable(1)
cout = cvx.Minimize(30*x+20*y)
avec = [  8*x+12*y >=24,
        12*x + 12*y >=36,
        2*x + y >= 4,
        x + y <= 5,
        x>=0,y>=0]
prob = cvx.Problem(cout,avec)
sol = prob.solve()
print((x.value,y.value))

print("dual variable", avec[0].dual_value)
print("dual variable", avec[1].dual_value)
print("dual variable", avec[2].dual_value)
print("dual variable", avec[3].dual_value)
print("dual variable", avec[4].dual_value)
print("dual variable", avec[5].dual_value)


(array([1.]), array([2.]))
(array([1.]), array([2.]))
dual variable [0.]
dual variable [0.83333333]
dual variable [10.]
dual variable [0.]
dual variable [0.]
dual variable [0.]


In [11]:
A = [[1 , 2, 3],[4,5,6]]
print(A)
b = np.sum(A)
print(b)
b = np.sum(A,axis=0)
print(b)
b = np.sum(A,axis=1)
print(b)

[[1, 2, 3], [4, 5, 6]]
21
[5 7 9]
[ 6 15]


In [12]:
whos

Variable   Type        Data/Info
--------------------------------
A          list        n=2
avec       list        n=6
b          ndarray     2: 2 elems, type `int64`, 16 bytes
cout       Minimize    minimize 30.0 * var40 + 20.0 * var41
cvx        module      <module 'cvxpy' from '/us<...>kages/cvxpy/__init__.py'>
np         module      <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
prob       Problem     minimize 30.0 * var40 + 2<...>        0.0 + -var41 <= 0
sc         module      <module 'scipy' from '/us<...>kages/scipy/__init__.py'>
sol        float64     70.0
x          Variable    var40
y          Variable    var41


In [1]:
# https://www.cvxpy.org/tutorial/functions/index.html

C = [[20.,40.,70.,50.],[100.,60.,90.,80.],[10.,110.,30.,200.]]
u = [400.,1500.,900.]
m = [700.,600.,1000,500.]
un = [1.,1.,1.,1.]
un3 = [1.,1.,1.]

V = cvx.Variable((3,4))
cout = cvx.Minimize(cvx.sum(C[0]*V[0])+cvx.sum(C[1]*V[1])+cvx.sum(C[2]*V[2]))
avec = [V >=0,  V*un<=u,  V.T*un3>=m]
prob = cvx.Problem(cout,avec)
sol = prob.solve()

print(V.value)

print(V.value@un)
print(V.value.T@un3)
sum(sum(V.value*C))

NameError: ignored

Expression(AFFINE, UNKNOWN, ())

In [5]:
!pip install glpk

    100% |████████████████████████████████| 163kB 4.8MB/s 
  Running setup.py bdist_wheel for glpk ... - error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-g1yps7i7/glpk/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-qdad7i2f --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'glpk' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-sXpGnM/python3.6-3.6.3=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc -I/usr/include/python3.6m -c src/glpk.c -o build/temp.linux-x86_64-3.6/src/glpk.o
  In fi